"use client"

import { useState } from "react"
import { GameHeader } from "@/components/game-header"
import { Button } from "@/components/ui/button"
import { CheckCircle, XCircle, ExternalLink, RotateCcw, Brain, Eye } from "lucide-react"
import Link from "next/link"

const imageComparisons = [
  {
    id: 1,
    image: "/images/image6.png",
    description:
      "This photo claims that the man with his hands raised high and his face covered in blood is a French spy standing next to Burkina Faso's president Traore.",
    isAI: true,
    explanation:
      "This photo was generated by AI. If you zoom in and look closely, you can see that Traore's fingers are distorted and the text on the soldier's uniform is garbled. These are typical characteristics of AI-generated images.",
    source: "https://factcheck.afp.com/doc.afp.com.62ZG862",
  },
  {
    id: 2,
    image: "/images/image7.jpg",
    description:
      "In the clashes between India and Pakistan, this image is believed to show a Pakistani truck carrying the wreckage of an Indian aircraft.",
    isAI: true,
    explanation:
      "This photo was generated by AI. The text on the truck's license plate is distorted and does not match the official license plates currently used in Pakistan.",
    source: "https://factcheck.afp.com/doc.afp.com.47964WD",
  },
  {
    id: 3,
    image: "/images/image8.png",
    description: "This image depicts animals in a city forest in India dodging bulldozers as they clear the forest.",
    isAI: true,
    explanation:
      "This photo was generated by AI. The wings of the bird are arranged irregularly, the two deer on the left look like one body, and the position of the other deer's legs is unnatural.",
    source: "https://factcheck.afp.com/doc.afp.com.39GU6G2",
  },
  {
    id: 4,
    image: "/images/image9.png",
    description: "This photo shows firefighters exhausted while trying to control a wildfire in South Korea.",
    isAI: true,
    explanation: "This photo was generated by AI. There is an extra hand near the firefighter's gloves.",
    source: "https://factcheck.afp.com/doc.afp.com.393T6KD",
  },
  {
    id: 5,
    image: "/images/image10.png",
    description:
      "This photo shows firefighters kneeling and praying in front of raging flames in Los Angeles, and is considered to be a true representation of the disaster scene.",
    isAI: true,
    explanation:
      "This photo was generated by AI. The image contains visual errors, such as inconsistent details on the fire truck and changes in the width and color of road markings.",
    source: "https://factcheck.afp.com/doc.afp.com.36XQ8KQ",
  },
]

export default function AIDetectionPage() {
  const [currentComparison, setCurrentComparison] = useState(0)
  const [selectedAnswer, setSelectedAnswer] = useState<boolean | null>(null)
  const [showResult, setShowResult] = useState(false)

  const comparison = imageComparisons[currentComparison]

  const handleAnswerSelect = (isAI: boolean) => {
    setSelectedAnswer(isAI)
  }

  const handleSubmit = () => {
    setShowResult(true)
  }

  const handleNext = () => {
    if (currentComparison < imageComparisons.length - 1) {
      setCurrentComparison((prev) => prev + 1)
      setSelectedAnswer(null)
      setShowResult(false)
    }
  }

  const handleRestart = () => {
    setCurrentComparison(0)
    setSelectedAnswer(null)
    setShowResult(false)
  }

  return (
    <div className="min-h-screen comic-bg">
      <GameHeader title="AI DETECTION LAB" subtitle="Identify AI-generated images" backUrl="/spot-the-fake" />

      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <div className="mb-6">
            <div className="flex items-center justify-between mb-4">
              <div className="comic-box bg-white p-3">
                <h2 className="comic-text text-2xl font-black">
                  ROUND {currentComparison + 1} / {imageComparisons.length}
                </h2>
              </div>
              <div className="comic-tag-accent">SPOT THE AI</div>
            </div>
            <div className="w-full bg-black h-4 border-2 border-black">
              <div
                className="bg-[#3a66ff] h-full transition-all duration-300"
                style={{ width: `${((currentComparison + 1) / imageComparisons.length) * 100}%` }}
              />
            </div>
          </div>

          <div className="comic-box bg-white p-6 mb-6">
            <div className="text-center mb-4">
              <img
                src={comparison.image || "/placeholder.svg"}
                alt="AI Detection Challenge"
                className="w-full max-w-2xl mx-auto border-3 border-black"
              />
            </div>
            <p className="text-center text-lg font-bold text-gray-700">{comparison.description}</p>
          </div>

          {!showResult ? (
            <div className="comic-box bg-white p-6">
              <h3 className="comic-text text-xl font-black mb-6 text-center">IS THIS IMAGE AI-GENERATED?</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                <div
                  className={`p-6 border-3 border-black cursor-pointer transition-all text-center ${
                    selectedAnswer === true ? "bg-[#3a66ff] text-white" : "bg-gray-100 hover:bg-gray-200"
                  }`}
                  onClick={() => handleAnswerSelect(true)}
                >
                  <Brain
                    className={`w-16 h-16 mx-auto mb-4 ${selectedAnswer === true ? "text-white" : "text-gray-400"}`}
                  />
                  <h4 className="comic-text text-lg font-black mb-2">AI-GENERATED</h4>
                  <p className="font-bold">This image was created by AI</p>
                </div>
                <div
                  className={`p-6 border-3 border-black cursor-pointer transition-all text-center ${
                    selectedAnswer === false ? "bg-[#00c16e] text-white" : "bg-gray-100 hover:bg-gray-200"
                  }`}
                  onClick={() => handleAnswerSelect(false)}
                >
                  <Eye
                    className={`w-16 h-16 mx-auto mb-4 ${selectedAnswer === false ? "text-white" : "text-gray-400"}`}
                  />
                  <h4 className="comic-text text-lg font-black mb-2">REAL PHOTO</h4>
                  <p className="font-bold">This is a genuine photograph</p>
                </div>
              </div>
              <Button
                onClick={handleSubmit}
                disabled={selectedAnswer === null}
                className="comic-button w-full bg-black text-white text-lg py-3"
              >
                SUBMIT ANSWER
              </Button>
            </div>
          ) : (
            <div className="comic-box bg-white p-6">
              <div className="text-center mb-6">
                <div className="flex items-center justify-center space-x-2 mb-4">
                  {selectedAnswer === comparison.isAI ? (
                    <CheckCircle className="w-8 h-8 text-[#00c16e]" />
                  ) : (
                    <XCircle className="w-8 h-8 text-[#ff3a3a]" />
                  )}
                  <h3 className="comic-text text-2xl font-black">
                    {selectedAnswer === comparison.isAI ? "CORRECT!" : "WRONG ANSWER"}
                  </h3>
                </div>

                <div className="comic-box-accent bg-[#3a66ff] text-white p-4 mb-4">
                  <p className="text-xl font-black">
                    CORRECT ANSWER: {comparison.isAI ? "AI-GENERATED" : "REAL PHOTO"}
                  </p>
                </div>

                <p className="text-lg font-bold text-gray-700 mb-6">{comparison.explanation}</p>
              </div>

              <div className="mb-6 p-4 bg-gray-100 border-2 border-black">
                <h4 className="font-black mb-2">Source:</h4>
                <a
                  href={comparison.source}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 font-bold hover:underline break-all"
                >
                  {comparison.source}
                </a>
              </div>

              <div className="flex flex-col sm:flex-row gap-4">
                {currentComparison < imageComparisons.length - 1 ? (
                  <Button onClick={handleNext} className="comic-button flex-1 bg-black text-white">
                    NEXT COMPARISON
                  </Button>
                ) : (
                  <Button onClick={handleRestart} className="comic-button flex-1 bg-black text-white">
                    <RotateCcw className="w-4 h-4 mr-2" />
                    TRY AGAIN
                  </Button>
                )}
                <Link href="/tool-library/ai-image-detection">
                  <Button className="comic-button flex-1 bg-[#3a66ff] text-white">
                    <ExternalLink className="w-4 h-4 mr-2" />
                    AI DETECTION GUIDE
                  </Button>
                </Link>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
